lista = list(["hola", "jiovanny", 26, 1.71])
lista2 = list(["es", " una", " lista", " para", " borrar"])
ordenar = list([1,4,33,6,7,55,8,9,54,23,10])

print(lista)
print("\n*********Metodo LEN*********")
print(lista.__len__())
print("\n*********Metodo APPEND*********")
print(lista.append("Xbox"))
print(lista)
print("\n*********Metodo INSERT*********")
print(lista.insert(0, "Series X"))
print(lista)
print("\n*********Metodo EXTEND*********")
print(lista.extend(["$1500", "Ingenieria", "en" , "Sistemas", 1.1440]))
print(lista)
print("\n*********Metodo POP*********")
print(lista.pop(10))
print(lista)
print("\n*********Metodo REMOVE*********")
print(lista.remove("$1500"))
print(lista)
print("\n*********Metodo CLEAR*********")
print(lista2.clear())
print(lista2)
print("\n*********Metodo SORT*********")
print(ordenar.sort(reverse=True))
print(ordenar)
print("\n*********Metodo REVERSE*********")
print(lista.reverse())
print(lista)